version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  app:
    build:
      context: /../.docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8089:80"
    networks:
      - php_advanced

